apiVersion : apps/v1
kind: Deployment
metadata:
  name: "fabmedicalsre-e3c1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "fabmedicalsre-e3c1"
  template:
    metadata:
      labels:
        app: "fabmedicalsre-e3c1"
    spec:
      containers:
        - name: "fabmedicalsre-e3c1"
          image: "fabmedicalsre.azurecr.io/fabmedicalsre"
          ports:
          - containerPort: 3000